### ISSUE TITLE
Backslash handling for PowerShell scripts is incorrect

### ISSUE THREAD

**Issue by gmckeown** [rouge-ruby/rouge#640]
The PowerShell lexer inherits a chunk of behaviour from the shell-script lexer. Since backslashes ("\\") are not escape characters in PowerShell, this results in some odd syntax-highlights when Windows-style paths are used:
![rouge_backslash_old](https://cloud.githubusercontent.com/assets/22765233/24261209/28c28c7e-0fee-11e7-99ab-d835aa452cf9.png)

I have taken a quick look to see if I can modify the powershell.rb to remove the special handling of backslash, but I can't figure out how to just "turn off" the rules without re-creating all of the affected states.

**Comment by gmckeown** [comment]
Original issue spotted on GitLab, issue reference: https://gitlab.com/gitlab-org/gitlab-ce/issues/29849

**Comment by thecliguy** [comment]
@aaroneg I hope you don't mind me reaching out to you like this, but as the original author of the powershell lexer I hoped you might be able to offer some guidance as to how to resolve the issue raised by @gmckeown _(I am encountering the exact same problem)_.

**Comment by aaroneg** [comment]
No clue. I hate Ruby so I did the bare minimum to make it /mostly/ work.
Perhaps someone more interested in writing lexers can be bribed to help?

**Comment by thecliguy** [comment]
@aaroneg I've studied the code more carefully and think I've identified the cause, now I just need some guidance as to how best to implement the fix... I won't CC you any further but if you do happen to have any thoughts I'd appreciate any feedback/guidance you can offer.

@gmckeown As mentioned in your original post
> PowerShell lexer inherits a chunk of behaviour from the shell-script lexer

My testing has revealed that there are two places within the shell lexer _(shell.rb)_ responsible for treating the backslashes in your example snippet as an escape character.

The paths within double quotes require removal of the following:
```diff
state :interp do
  rule /\\$/, Str::Escape # line continuation
- rule /\\./, Str::Escape
```

The path without quotes requires removal of the above plus the following:
```diff
state :data do
  rule /\s+/, Text
- rule /\\./, Str::Escape
```

We therefore require a means of blocking inheritance for these two offending lines. I'm not sure how best to achieve this...

One option is to simply copy `state :interp do` and `state :data do` from `shell.rb` to `powershell.rb`, removing `rule /\\./, Str::Escape`.

Have you any thoughts?

**Comment by aaroneg** [comment]
Yeah honestly trying to parse the shell lexer well enough to know what part
of the spaghetti to override is a bit of a challenge. Jneen might be able
to help you discover what to do if you ask nicely, she was kind enough to
reformat the powershell lexer so it met her coding standards.

**Comment by gmckeown** [comment]
@thecliguy I took a stab at this the other weekend and came up with the lexer below. Haven't had time to properly test it yet...
```
# -*- coding: utf-8 -*- #

module Rouge
  module Lexers
    load_lexer 'shell.rb'

    class Powershell < Shell
      title 'powershell'
      desc 'powershell'
      tag 'powershell'
      aliases 'posh'
      filenames '*.ps1', '*.psm1', '*.psd1'
      mimetypes 'text/x-powershell'

      ATTRIBUTES = %w(
        CmdletBinding ConfirmImpact DefaultParameterSetName HelpURI SupportsPaging
        SupportsShouldProcess PositionalBinding
      ).join('|')

      KEYWORDS = %w(
        Begin Exit Process Break Filter Return Catch Finally Sequence Class For
        Switch Continue ForEach Throw Data From Trap Define Function Try Do If
        Until DynamicParam In Using Else InlineScript Var ElseIf Parallel While
        End Param Workflow
      ).join('|')

      KEYWORDS_TYPE = %w(
        bool byte char decimal double float int long object sbyte
        short string uint ulong ushort
      ).join('|')

      OPERATORS = %w(
        -split -isplit -csplit -join -is -isnot -as -eq -ieq -ceq -ne -ine
        -cne -gt -igt -cgt -ge -ige -cge -lt -ilt -clt -le -ile -cle -like
        -ilike -clike -notlike -inotlike -cnotlike -match -imatch -cmatch
        -notmatch -inotmatch -cnotmatch -contains -icontains -ccontains
        -notcontains -inotcontains -cnotcontains -replace -ireplace
        -creplace -band -bor -bxor -and -or -xor \. & = \+= -= \*= \/= %=
      ).join('|')

      BUILTINS = %w(
        Add-Content Add-History Add-Member Add-PSSnapin Clear-Content
        Clear-Item Clear-Item Property Clear-Variable Compare-Object
        ConvertFrom-SecureString Convert-Path ConvertTo-Html
        ConvertTo-SecureString Copy-Item Copy-ItemProperty Export-Alias
        Export-Clixml Export-Console Export-Csv ForEach-Object
        Format-Custom Format-List Format-Table Format-Wide
        Get-Acl Get-Alias Get-AuthenticodeSignature Get-ChildItem
        Get-Command Get-Content Get-Credential Get-Culture Get-Date
        Get-EventLog Get-ExecutionPolicy Get-Help Get-History
        Get-Host Get-Item Get-ItemProperty Get-Location Get-Member
        Get-PfxCertificate Get-Process Get-PSDrive Get-PSProvider
        Get-PSSnapin Get-Service Get-TraceSource Get-UICulture
        Get-Unique Get-Variable Get-WmiObject Group-Object
        Import-Alias Import-Clixml Import-Csv Invoke-Expression
        Invoke-History Invoke-Item Join-Path Measure-Command
        Measure-Object Move-Item Move-ItemProperty New-Alias
        New-Item New-ItemProperty New-Object New-PSDrive New-Service
        New-TimeSpan New-Variable Out-Default Out-File Out-Host Out-Null
        Out-Printer Out-String Pop-Location Push-Location Read-Host
        Remove-Item Remove-ItemProperty Remove-PSDrive Remove-PSSnapin
        Remove-Variable Rename-Item Rename-ItemProperty Resolve-Path
        Restart-Service Resume-Service Select-Object Select-String
        Set-Acl Set-Alias Set-AuthenticodeSignature Set-Content Set-Date
        Set-ExecutionPolicy Set-Item Set-ItemProperty Set-Location
        Set-PSDebug Set-Service Set-TraceSource Set-Variable Sort-Object
        Split-Path Start-Service Start-Sleep Start-Transcript Stop-Process
        Stop-Service Stop-Transcript Suspend-Service Tee-Object Test-Path
        Trace-Command Update-FormatData Update-TypeData Where-Object
        Write-Debug Write-Error Write-Host Write-Output Write-Progress
        Write-Verbose Write-Warning ac asnp cat cd chdir clc clear clhy
        cli clp cls clv cnsn compare copy cp cpi cpp curl cvpa dbp del
        diff dir dnsn ebp echo epal epcsv epsn erase etsn exsn fc fl
        foreach ft fw gal gbp gc gci gcm gcs gdr ghy gi gjb gl gm gmo
        gp gps group gsn gsnp gsv gu gv gwmi h history icm iex ihy ii
        ipal ipcsv ipmo ipsn irm ise iwmi iwr kill lp ls man md measure
        mi mount move mp mv nal ndr ni nmo npssc nsn nv ogv oh popd ps
        pushd pwd r rbp rcjb rcsn rd rdr ren ri rjb rm rmdir rmo rni rnp
        rp rsn rsnp rujb rv rvpa rwmi sajb sal saps sasv sbp sc select
        set shcm si sl sleep sls sort sp spjb spps spsv start sujb sv
        swmi tee trcm type wget where wjb write \% \?
      ).join('|')

      # Override from Shell
      state :interp do
        rule /`$/, Str::Escape # line continuation
        rule /./, Str::Escape
        rule /\$\(\(/, Keyword, :math
        rule /\$\(/, Keyword, :paren
        rule /\${#?/, Keyword, :curly
        rule /\$#?(\w+|.)/, Name::Variable
      end

      # Override from Shell
      state :double_quotes do
        # NB: "abc$" is literally the string abc$.
        # Here we prevent :interp from interpreting $" as a variable.
        rule /(?:\$#?)?"/, Str::Double, :pop!
        mixin :interp
        rule /[^"`$]+/, Str::Double
      end

      # Override from Shell
      state :data do
        rule /\s+/, Text
        rule /\$?"/, Str::Double, :double_quotes
        rule /\$'/, Str::Single, :ansi_string

        rule /'/, Str::Single, :single_quotes

        rule /\*/, Keyword

        rule /;/, Text
        rule /[^=\*\s{}()$"'`\\<]+/, Text
        rule /\d+(?= |\Z)/, Num
        rule /</, Text
        mixin :interp
      end

      prepend :basic do
        rule %r(<#[\s,\S]*?#>)m, Comment::Multiline
        rule /#.*$/, Comment::Single
        rule /\b(#{OPERATORS})\s*\b/i, Operator
        rule /\b(#{ATTRIBUTES})\s*\b/i, Name::Attribute
        rule /\b(#{KEYWORDS})\s*\b/i, Keyword
        rule /\b(#{KEYWORDS_TYPE})\s*\b/i, Keyword::Type
        rule /\bcase\b/, Keyword, :case
        rule /\b(#{BUILTINS})\s*\b(?!\.)/i, Name::Builtin
      end
    end
  end
end
```

**Comment by gmckeown** [comment]
The above should also include the fix for back-ticks, but looking at it there might be an error in the :interp override.
```
       rule /./, Str::Escape
```
Should probably be:
```
       rule /`./, Str::Escape
```
To be honest, my testing directory for this was an absolute mess, so I can only hope this is the right version of the file ;)

**Comment by thecliguy** [comment]
@gmckeown I've tried your powershell.rb. See comparisons below:

**Original version:**
![powershell rb_original](https://cloud.githubusercontent.com/assets/23440389/25097791/dee3d6e4-239d-11e7-88e4-4e0b83fbdad0.png)

**gmckeown's version:**
![powershell rb_gmckeown](https://cloud.githubusercontent.com/assets/23440389/25097823/040f0a38-239e-11e7-836f-4c47fd00373e.png)

**thecliguy's version (with the changes outlined in the 5th post):**
![powershell rb_thecliguy](https://cloud.githubusercontent.com/assets/23440389/25097801/ea2cfd00-239d-11e7-911b-3259754a5010.png)

**Comment by gmckeown** [comment]
I think the main issue you see with my version is the error i mention above with the escape line in interp -- it's just matching all characters as escape characters (hence they're red). Not sure about the variables being in a different colour...

The version based on the changes described by thecliguy look pretty good anyway.

**Comment by thecliguy** [comment]
Apologies, I forgot to make the amendment that you had suggested.

I've now updated your version and replaced:
```
rule /./, Str::Escape
``` 

with:

```
rule /`./, Str::Escape
``` 

Here's the result I'm getting, looks good:
![gmckeownv2](https://cloud.githubusercontent.com/assets/23440389/25099624/0102f564-23a5-11e7-960e-25c2daf9dfad.png)

**Comment by gmckeown** [comment]
Good stuff! I've got a small selection of scripts I can test against to see whether there are any regressions. If you have other scripts you can test with, please compare those as well. If all looks good, we can stick in a pull request with the changes -- you can do it if you want, or I'm happy to submit that. The maintainer seems tied up with other stuff at the moment; my pull request for the backticks fix has been pending for 25 days so far.

**Comment by aaroneg** [comment]
Yeah, mine took a while too. She seems to deal with them in batches every
so often. Thank you all for taking the time to improve this, I appreciate
it,  as someone who will probably have to use gitlab again at some point.

**Comment by gmckeown** [comment]
Here's the exact powershell.rb I've now tested, and for my limited selection of PowerShell scripts, this appears to highlight everything the same except for the fixed backslashes and backticks.
```
# -*- coding: utf-8 -*- #

module Rouge
  module Lexers
    load_lexer 'shell.rb'

    class Powershell < Shell
      title 'powershell'
      desc 'powershell'
      tag 'powershell'
      aliases 'posh'
      filenames '*.ps1', '*.psm1', '*.psd1'
      mimetypes 'text/x-powershell'

      ATTRIBUTES = %w(
        CmdletBinding ConfirmImpact DefaultParameterSetName HelpURI SupportsPaging
        SupportsShouldProcess PositionalBinding
      ).join('|')

      KEYWORDS = %w(
        Begin Exit Process Break Filter Return Catch Finally Sequence Class For
        Switch Continue ForEach Throw Data From Trap Define Function Try Do If
        Until DynamicParam In Using Else InlineScript Var ElseIf Parallel While
        End Param Workflow
      ).join('|')

      KEYWORDS_TYPE = %w(
        bool byte char decimal double float int long object sbyte
        short string uint ulong ushort
      ).join('|')

      OPERATORS = %w(
        -split -isplit -csplit -join -is -isnot -as -eq -ieq -ceq -ne -ine
        -cne -gt -igt -cgt -ge -ige -cge -lt -ilt -clt -le -ile -cle -like
        -ilike -clike -notlike -inotlike -cnotlike -match -imatch -cmatch
        -notmatch -inotmatch -cnotmatch -contains -icontains -ccontains
        -notcontains -inotcontains -cnotcontains -replace -ireplace
        -creplace -band -bor -bxor -and -or -xor \. & = \+= -= \*= \/= %=
      ).join('|')

      BUILTINS = %w(
        Add-Content Add-History Add-Member Add-PSSnapin Clear-Content
        Clear-Item Clear-Item Property Clear-Variable Compare-Object
        ConvertFrom-SecureString Convert-Path ConvertTo-Html
        ConvertTo-SecureString Copy-Item Copy-ItemProperty Export-Alias
        Export-Clixml Export-Console Export-Csv ForEach-Object
        Format-Custom Format-List Format-Table Format-Wide
        Get-Acl Get-Alias Get-AuthenticodeSignature Get-ChildItem
        Get-Command Get-Content Get-Credential Get-Culture Get-Date
        Get-EventLog Get-ExecutionPolicy Get-Help Get-History
        Get-Host Get-Item Get-ItemProperty Get-Location Get-Member
        Get-PfxCertificate Get-Process Get-PSDrive Get-PSProvider
        Get-PSSnapin Get-Service Get-TraceSource Get-UICulture
        Get-Unique Get-Variable Get-WmiObject Group-Object
        Import-Alias Import-Clixml Import-Csv Invoke-Expression
        Invoke-History Invoke-Item Join-Path Measure-Command
        Measure-Object Move-Item Move-ItemProperty New-Alias
        New-Item New-ItemProperty New-Object New-PSDrive New-Service
        New-TimeSpan New-Variable Out-Default Out-File Out-Host Out-Null
        Out-Printer Out-String Pop-Location Push-Location Read-Host
        Remove-Item Remove-ItemProperty Remove-PSDrive Remove-PSSnapin
        Remove-Variable Rename-Item Rename-ItemProperty Resolve-Path
        Restart-Service Resume-Service Select-Object Select-String
        Set-Acl Set-Alias Set-AuthenticodeSignature Set-Content Set-Date
        Set-ExecutionPolicy Set-Item Set-ItemProperty Set-Location
        Set-PSDebug Set-Service Set-TraceSource Set-Variable Sort-Object
        Split-Path Start-Service Start-Sleep Start-Transcript Stop-Process
        Stop-Service Stop-Transcript Suspend-Service Tee-Object Test-Path
        Trace-Command Update-FormatData Update-TypeData Where-Object
        Write-Debug Write-Error Write-Host Write-Output Write-Progress
        Write-Verbose Write-Warning ac asnp cat cd chdir clc clear clhy
        cli clp cls clv cnsn compare copy cp cpi cpp curl cvpa dbp del
        diff dir dnsn ebp echo epal epcsv epsn erase etsn exsn fc fl
        foreach ft fw gal gbp gc gci gcm gcs gdr ghy gi gjb gl gm gmo
        gp gps group gsn gsnp gsv gu gv gwmi h history icm iex ihy ii
        ipal ipcsv ipmo ipsn irm ise iwmi iwr kill lp ls man md measure
        mi mount move mp mv nal ndr ni nmo npssc nsn nv ogv oh popd ps
        pushd pwd r rbp rcjb rcsn rd rdr ren ri rjb rm rmdir rmo rni rnp
        rp rsn rsnp rujb rv rvpa rwmi sajb sal saps sasv sbp sc select
        set shcm si sl sleep sls sort sp spjb spps spsv start sujb sv
        swmi tee trcm type wget where wjb write \% \?
      ).join('|')

      # Override from Shell
      state :interp do
        rule /`$/, Str::Escape # line continuation
        rule /`./, Str::Escape
        rule /\$\(\(/, Keyword, :math
        rule /\$\(/, Keyword, :paren
        rule /\${#?/, Keyword, :curly
        rule /\$#?(\w+|.)/, Name::Variable
      end

      # Override from Shell
      state :double_quotes do
        # NB: "abc$" is literally the string abc$.
        # Here we prevent :interp from interpreting $" as a variable.
        rule /(?:\$#?)?"/, Str::Double, :pop!
        mixin :interp
        rule /[^"`$]+/, Str::Double
      end

      # Override from Shell
      state :data do
        rule /\s+/, Text
        rule /\$?"/, Str::Double, :double_quotes
        rule /\$'/, Str::Single, :ansi_string

        rule /'/, Str::Single, :single_quotes

        rule /\*/, Keyword

        rule /;/, Text
        rule /[^=\*\s{}()$"'`\\<]+/, Text
        rule /\d+(?= |\Z)/, Num
        rule /</, Text
        mixin :interp
      end

      prepend :basic do
        rule %r(<#[\s,\S]*?#>)m, Comment::Multiline
        rule /#.*$/, Comment::Single
        rule /\b(#{OPERATORS})\s*\b/i, Operator
        rule /\b(#{ATTRIBUTES})\s*\b/i, Name::Attribute
        rule /\b(#{KEYWORDS})\s*\b/i, Keyword
        rule /\b(#{KEYWORDS_TYPE})\s*\b/i, Keyword::Type
        rule /\bcase\b/, Keyword, :case
        rule /\b(#{BUILTINS})\s*\b(?!\.)/i, Name::Builtin
      end
    end
  end
end
```

**Comment by gmckeown** [comment]
Seems like it's probably an idea to get a PR in as soon as possible. Looking at other requests, Jeanine appears to be very thorough in reviewing PRs :)

Any further comments about this specific, proposed update, please post them against #660.

**Comment by thecliguy** [comment]
Apologies for not having replied sooner, first day back to work after the Easter bank holiday - had a few fires to extinguish (I'm a sysadmin).

I will try and check the syntax highlighting of some of my other PowerShell scripts tonight.
________________________________

**Comment by gmckeown** [comment]
Heh, no need to apologise for my impatience! I appreciate  your help on this :)

**Comment by jneen** [comment]
@thecliguy - you can block inheritance of those rules by using `prepend` and providing a rule that would match beforehand - like `rule /\\/, Text` or similar.

**Comment by thecliguy** [comment]
@gmckeown I've done some further testing and discovered a problem with multi-line commands.

By _multi-line command_ I mean a command consisting of multiple lines that has been formatted so that it may be copy and pasted directly into a console window. This is achieved by ending the last line with a semi-colon and all previous lines with a semi-colon and a backtick.

The sample powershell.rb that you posted a few comments above has the effect of inserting a blank line between the commands:
![gmckeown](https://cloud.githubusercontent.com/assets/23440389/25567528/8a11d5f4-2de7-11e7-9fc8-9bea1b7d3697.png)

I've therefore had to revert to the changes I outlined in the fifth post, removal of two lines in `shell.rb`. But I don't know if your changes are preferable to mine - this is not my forte.

I'm a bit lost - the problem I'm seeing relates to the backtick character, so should I be looking at issue 660? https://github.com/jneen/rouge/pull/660

**Comment by gmckeown** [comment]
@thecliguy I can't reproduce this issue using the lexer included in #660 -- can you try with that version?

As an aside I have noticed an issue with the fact that I've removed backslash handling from that lexer -- visually it seems OK, but the lexer debug output shows an error since it's not matching them any more. Currently awaiting some advice on using prepend for over-rides, which should fix this issue anyway (as we're forced to define new rules for the backslash when using prepend). That's part of the conversation on #660.

**Comment by thecliguy** [comment]
@gmckeown I just tried https://github.com/gmckeown/rouge/blob/f8af49441e76e7f90d59d180fb9b142028d860bc/lib/rouge/lexers/powershell.rb but now Jekyll fails to build:
```
/var/lib/gems/2.3.0/gems/rouge-1.11.1/lib/rouge/lexer.rb:371:in `load': /var/lib/gems/2.3.0/gems/rouge-1.11.1/lib/rouge/lexers/powershell.rb:126: s keyword_end, expecting end-of-input (SyntaxError)
```

**Comment by gmckeown** [comment]
@thecliguy Hmmm... I've been testing with the rackup method described in the rouge readme and that works fine. Also testing with GitLab and no issues there.
I've not used Jekyll before, so have just installed it to test (v3.4.3 on one of my Ubuntu 16.04.2 boxes) and created a basic post with some highlighted code. Ran it like so:
```
gmckeown@centauri:~/Development/Scratch/rougetest$ jekyll serve -H 0.0.0.0 -P 4155
Configuration file: /mnt/network/home/gmckeown/Development/Scratch/rougetest/_config.yml
Configuration file: /mnt/network/home/gmckeown/Development/Scratch/rougetest/_config.yml
            Source: /mnt/network/home/gmckeown/Development/Scratch/rougetest
       Destination: /mnt/network/home/gmckeown/Development/Scratch/rougetest/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 1.838 seconds.
 Auto-regeneration: enabled for '/mnt/network/home/gmckeown/Development/Scratch/rougetest'
Configuration file: /mnt/network/home/gmckeown/Development/Scratch/rougetest/_config.yml
    Server address: http://0.0.0.0:4155/
  Server running... press ctrl-c to stop.
```
And the output was:
![jekyll rouge powershell](https://cloud.githubusercontent.com/assets/22765233/25576967/b2e0edf8-2e5a-11e7-97d9-352a00ecf7b1.png)

**Comment by thecliguy** [comment]
@gmckeown Apologies, a stupid mistake on my part, I somehow failed to copy the first two lines of https://github.com/gmckeown/rouge/blob/f8af49441e76e7f90d59d180fb9b142028d860bc/lib/rouge/lexers/powershell.rb

I've rectified that and now the site builds, however I still get the blank lines each command.

I'm running Jekyll version `3.3.1` with the [Hyde](https://github.com/poole/hyde) theme.

Thanks for all your help, I really appreciate it. Unfortunately I'll have to bail out now, I just don't have the time to try and identify the culprit - perhaps its the version of Jekyll, perhaps its the theme... What a minefield. At some point I'll try and substitute my current theme with another and see if that works.

**Comment by aaroneg** [comment]
This was addresses by #660 and can be closed.
